# Generated by Django 4.2.2 on 2023-06-16 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_category_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
