# Generated by Django 4.2.2 on 2023-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_tag_alter_category_options_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
